### ISSUE TITLE
Determine best approach for converting existing Java keystore to PKCS12

### ISSUE THREAD

**Issue by amoose** [department-of-veterans-affairs/connect_vbms#108]
Can we create a rake task for this conversion? 
Also, determine best method for extraction and conversion of `vbms_server_cert` since PKCS12 doesn't support trustedCertEntry

**Comment by harrisj** [comment]
As I understand it, the issue is that Ruby/OpenSSL do not want to use the Java keystore objects provided by the VA VBMS admins. And the PKCS12 format does not allow the inclusion of certificates within in (only private key entries or the like). So, this will require a few changes:

- [ ] A script for splitting a jks file into a pkcs12 file and a separate certificate
- [ ] A new environment variable/argument to the VBMS::Client for the certificate
- [ ] Changes to the documentation as well

**Comment by amoose** [comment]
So far so good, committed to current encryption branch: https://github.com/department-of-veterans-affairs/connect_vbms/commit/b30033b2d9a2db2c23a5694707a73061e1212f24

Keep this open until we update documentation too
