### ISSUE TITLE
Run tests without hitting the endpoints

### ISSUE THREAD

**Issue by amoose** [department-of-veterans-affairs/connect_vbms#20]
Currently, tests of type: `integration` are skipped in CI because they attempt to touch an actual API. We need to create mocked responses for these tests in order to run our entire test suite without API credentials.

<hr>

Questions:
  - [x] Are there any security issues with mocking these API endpoints? should we use fixtures that are shared privately or are mocked endpoints ok? **No**
  - [x] Are there any PII issues to consider? is there any risk of exposing PII in the test env?  **No**

**Comment by llimllib** [comment]
Amen. The reason they haven't been is that it's a big pain: we're basically going to have to generate a keypair and learn how VBMS generates their messages. The encrypted messages have a five-minute (IIRC) time window in which they're valid; thus unless we do some system-clock hacking, we're going to have to generate fresh messages for each test rather than use fixtures. 

My answers to your Qs, which are not definitive:

1. My feeling is that you could reverse engineer the API messages from what we have already, there's no additional security risk in mocking responses

2. there should be no PII to consider in the test env AFAIK

**Comment by harrisj** [comment]
I suppose we could look for an environment setting like CONNECT=1 and if it is present, the tests could hit the endpoints and if absent, we could set up webmocks for those integration tests.

**Comment by harrisj** [comment]
It seems like there are two options for handling the issue of time-sensitive signatures:

1. In the integration tests that don't hit the remote endpoints, simply mock the `VBMS::Client::send` method to just return fixture data. This is basically a giant switch statement keyed off of the input URL and it allows you to avoid any time freezing or URL mocking, but it also runs counter to an integration test by bypassing a fair amount of code that would be run otherwise. It would be possible to move this mocking further down by passing the source URL to the `decrypt_message_xml` method, but still you would skip some code.
2. Alternatively, we can use the [webmock](https://github.com/bblimke/webmock) gem to mock the web responses and [timecop](https://github.com/travisjeffery/timecop) gem to mock the system clock in integration tests to match the time when the mocked web response was captured. This would mean that the persons grabbing the web responses must note somewhere the time the responses were captured. These responses could also be used for unit testing the decryption methods.

**Comment by alex** [comment]
IMO we should have two sets of tests: one that are really designed to run
as integration tests, and then a seperate set of more unit-testy stuff that
really excersises all that logic.

On Mon, Aug 24, 2015 at 2:48 PM, Jacob Harris <notifications@github.com>
wrote:

> It seems like there are two options for handling the issue of
> time-sensitive signatures:
>
>    1. In the integration tests that don't hit the remote endpoints,
>    simply mock the VBMS::Client::send method to just return fixture data.
>    This is basically a giant switch statement keyed off of the input URL and
>    it allows you to avoid any time freezing or URL mocking, but it also runs
>    counter to an integration test by bypassing a fair amount of code that
>    would be run otherwise. It would be possible to move this mocking further
>    down by passing the source URL to the decrypt_message_xml method, but
>    still you would skip some code.
>    2. Alternatively, we can use the webmock
>    <https://github.com/bblimke/webmock> gem to mock the web responses and
>    timecop <https://github.com/travisjeffery/timecop> gem to mock the
>    system clock in integration tests to match the time when the mocked web
>    response was captured. This would mean that the persons grabbing the web
>    responses must note somewhere the time the responses were captured. These
>    responses could also be used for unit testing the decryption methods.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/20#issuecomment-134335444>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by harrisj** [comment]
Okay, so I was a little naive about just capturing the responses, since using those encrypted XML files would mean the test server would need access to the remote VBMS public key (for verifying signatures) and the test user's private key (for decrypting the XML). Neither of these should be checked into source control really, so a better approach is to take advantage of the fact that we already have a `test_keystore.jks` in the `spec/fixtures` directory and a `do_wsse.sh` script that can encrypt XML documents with WS-Security. Even when we phase it out from being called by the Ruby gem, we can still use it for these tests to encrypt mocked responses on demand. This lets us edit the payloads how we want and also avoid the need to use timecop, so this is the plan I'm going with.

**Comment by harrisj** [comment]
Fixed in #42
