### ISSUE TITLE
Determine if there is a more elegant method for processing multipart messages

### ISSUE THREAD

**Issue by amoose** [department-of-veterans-affairs/connect_vbms#55]
We're including the Mail gem in order to process the multipart messages; let's see if there is a simpler method for this processing.

**Comment by harrisj** [comment]
We should be able to unravel/emulate the multipart processing so we don't need to include all the Mail functionality. In an ideal world, maybe we'd make that a separate gem that even Mail could include ;)

**Comment by harrisj** [comment]
Upon further discussion, we decided to keep the dependency on the Mail gem instead of replicating its multipart splitting functionality. In an ideal world, the Mail gem would extract the multipart processing as a separate gem, but it is unlikely we will be able to match their experience and tests for real-world cases in which multipart has been used and abused.
